---
- name: REDIS_EXPORTER | Setup container
  include_tasks: docker.yml
  tags:
    - install
  when: redis_exporter_dockerize

- name: REDIS_EXPORTER | Install
  include_tasks: install.yml
  tags:
    - install
  when: not redis_exporter_dockerize

- name: REDIS_EXPORTER | Configure
  include_tasks: config.yml
  tags:
    - configure
  when: not redis_exporter_dockerize

- name: REDIS_EXPORTER | Service
  include_tasks: service.yml
  tags:
    - service
  when: not redis_exporter_dockerize
